Use versioned reference to action
IncQueryLabs/incquery-suite-bridge-autosar-uml-action pull request #6
Opened 2023-10-19 13:38 UTC by kkadosa

Removed steps so the workflow actually works
Updated readme slightly to clarify what exactly the action does

2023-10-19 14:02 UTC, dandrid requested changes

2023-12-05 12:56 UTC, kkadosa commented on readme.md
> +## What does the workflow do?
The quotation literally contains that.

2023-12-05 13:15 UTC, dandrid commented on readme.md
> +## What does the workflow do?
We have an action, which is reusable, which:

1. Downloads and installs the IncQuery AUTOSAR-UML Bridge, if it is not already installed
2. Runs the IncQuery AUTOSAR-UML Bridge

We have an example workflow, which demonstrates a potential usage of the AUTOSAR-UML Bridge Action:

1. Checks out the Git repository
3. Backups up the EA Project File
4. Runs IncQuery AUTOSAR-UML Bridge Action
5. Pushes the updated model

The users would mainly like to reuse the the Action (which is about how to run the AUTOSAR-UML Bridge). 

The current section mixes both the Workflow and the Action. I think we should separate these. In the first section, we could add some details on how the AUTOSAR-UML Bridge Action works, encouraging the users to reuse the Action in their own Workflows. Then we could have an Example Workflow section, which details how the example works, and shows a usage example for the AUTOSAR-UML Bridge Action.

2023-12-05 13:22 UTC, kkadosa commented on readme.md
> +## What does the workflow do?
No, the current section deals purely with the workflow. It is a subsection in the section dealing with the action. The basic description of the action is directly above this change, within the image, and is then followed by more technical sections.

2023-12-05 13:42 UTC, dandrid commented on readme.md
>   (unless already installed on the GitHub Runner), then executes a transformation on an input AUTSOAR model,
AUTSOAR

2023-12-05 18:08 UTC, dandrid approved these changes

2023-12-06 09:25 UTC, merged